### ISSUE TITLE
Yjs v13 Room syncing error

### ISSUE THREAD

**Issue by boschDev** [y-js/yjs#105]
When I am trying to to load multiple rooms y rooms at once I will get this error. The yjs folder in linked to the yjs folder in the node_modules. This error will appear by the syncing.
```
Error: Unable to receive message
    at /home/vagrant/Code/services/websocket-service/node_modules/yjs/y.node.js:5119:17
    at Y$1.transact (/home/vagrant/Code/services/websocket-service/node_modules/yjs/y.node.js:5430:7)
    at Connector.computeMessage (/home/vagrant/Code/services/websocket-service/node_modules/yjs/y.node.js:5113:9)
    at messages.forEach.m (/home/vagrant/Code/services/websocket-service/node_modules/yjs/y.node.js:5095:18)
    at Array.forEach (<anonymous>)
    at checkAuth.then.authPermissions (/home/vagrant/Code/services/websocket-service/node_modules/yjs/y.node.js:5094:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
You tried to sync with a Yjs instance that has a different protocol version
      (You: 91, Client: 91).
      
Captured an unhandled rejection! Error: Integer out of range!
    at BinaryDecoder.readVarUint (/home/vagrant/Code/services/websocket-service/node_modules/yjs/y.node.js:699:15)
    at readStateSet (/home/vagrant/Code/services/websocket-service/node_modules/yjs/y.node.js:926:25)
    at readSyncStep1 (/home/vagrant/Code/services/websocket-service/node_modules/yjs/y.node.js:1111:14)
    at Connector.computeMessage (/home/vagrant/Code/services/websocket-service/node_modules/yjs/y.node.js:5110:7)
    at messages.forEach.m (/home/vagrant/Code/services/websocket-service/node_modules/yjs/y.node.js:5095:18)
    at Array.forEach (<anonymous>)
    at checkAuth.then.authPermissions (/home/vagrant/Code/services/websocket-service/node_modules/yjs/y.node.js:5094:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by dmonad** [comment]
Hey @boschDev 

I'm just guessing that you are not using y-websockets-server. Because this works perfectly fine for me.

I adapted y-websockets-server for the new release. So you probably also have to do some modifications.  protocol version `91` does not yet exist. So I guess that you are not correctly passing over the buffer object to Yjs.

Yjs does no longer encode messages as Strings. The connector accepts ArrayBuffers and Node Buffers only. Make sure you are not passing a string instead.

**Comment by dmonad** [comment]
If you provide me more information I can help you better ;)
