### ISSUE TITLE
Support for build systems

### ISSUE THREAD

**Issue by dmonad** [y-js/yjs#51]
I open this issue to discuss some problems of build systems, because I'm not very familiar with all the build systems that exist out there. Currently only globals and npm are supported. Now I plan to create support for es6 module imports too. If you know of any problems of your build process, please report them here (even if you were able to fix them).

Some people have problems using Yjs with ember-cli. Apparantly the source maps do not work correctly in the uglified code. [This is a known problem](https://github.com/mishoo/UglifyJS2/issues/863) and was fixed. I'll wait for the next release, update uglifyjs, and hope that this will fix the problem.

Furthermore it seems that the extention *.es6 is not recognized by broccolijs. I plan to rename the *.es6 files to *.es6.js to avoid this problem (even if .es6 is a valid extention). In order to avoid breaking automated build systems, I'll release these changes together in the next version of Yjs.

**Comment by DadaMonad** [comment]
In nodejs it is likely that the file extention `.mjs` will be used to recognize es2015 modules. In the future, this will be preferred as the file-extention for es2015 modules. [See here](https://github.com/nodejs/node-eps/blob/5dae5a537c2d56fbaf23aaf2ae9da15e74474021/002-es6-modules.md#51-determining-if-source-is-an-es-module)

[Rollup.js](http://rollupjs.org/) is currently lobbying for the package-entry `jsnext:main` for all libraries. I plan to use rollup for the build-process in the next version of Yjs. The package.json will look like this:

```
{ ..
  "main": "y.js",
  "jsnext:main": "y.m.js",
}
```

This, hopefully, also resolves the broccoli problems.

**Comment by lukebarlow** [comment]
I'm not sure if this is exactly what you're after, but I've got yjs working with babel and webpack, and thought I'd share the configuration in case that's useful, so it's here

https://github.com/lukebarlow/yjs-jigsaw-es6-imports

**Comment by DadaMonad** [comment]
This will be really helpful to others using webpack, thanks! I haven't used Webpack yet. I'll give it a try next week. Is this really necessary?:

```
plugins: [
  new webpack.IgnorePlugin(/SpecHelper/),
  new webpack.IgnorePlugin(/.*\.md/),
]
```

**Comment by lukebarlow** [comment]
Yes, but probably they can be got rid of with some small tweaks to the yjs code. Here's the error messages that pop up without those lines, in case that's helpful. 

```
WARNING in ./~/yjs/src/Notes.md
Module parse failed: /Projects/fork/yjs-jigsaw-es6-imports/node_modules/yjs/src/Notes.md Unexpected character '#' (2:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '#' (2:0)
    at Parser.pp$4.raise (/Projects/fork/yjs-jigsaw-es6-imports/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/Projects/fork/yjs-jigsaw-es6-imports/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/Projects/fork/yjs-jigsaw-es6-imports/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/Projects/fork/yjs-jigsaw-es6-imports/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.parse (/Projects/fork/yjs-jigsaw-es6-imports/node_modules/acorn/dist/acorn.js:515:10)
    at Object.parse (/Projects/fork/yjs-jigsaw-es6-imports/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Projects/fork/yjs-jigsaw-es6-imports/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Projects/fork/yjs-jigsaw-es6-imports/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Projects/fork/yjs-jigsaw-es6-imports/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Projects/fork/yjs-jigsaw-es6-imports/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Projects/fork/yjs-jigsaw-es6-imports/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Projects/fork/yjs-jigsaw-es6-imports/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Projects/fork/yjs-jigsaw-es6-imports/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
 @ ./~/yjs/src ^\.\/.*$

ERROR in ./~/yjs/src/SpecHelper.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../y-indexeddb/src/IndexedDB.js in /Projects/fork/yjs-jigsaw-es6-imports/node_modules/yjs/src
 @ ./~/yjs/src/SpecHelper.js 13:0-45

ERROR in ./~/yjs/src/SpecHelper.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../y-leveldb/src/LevelDB.js in /Projects/fork/yjs-jigsaw-es6-imports/node_modules/yjs/src
 @ ./~/yjs/src/SpecHelper.js 15:2-43

ERROR in ./~/yjs/src/SpecHelper.js
Module not found: Error: Cannot resolve module 'seedrandom' in /Projects/fork/yjs-jigsaw-es6-imports/node_modules/yjs/src
 @ ./~/yjs/src/SpecHelper.js 30:18-39
```
