### ISSUE TITLE
debug module is missing

### ISSUE THREAD

**Issue by joshmarinacci** [y-js/yjs#66]
if I require yjs using npm I get a runtime error saying module debug is missing. I see it is used in y.js but is not declared in the package.json. Is this by design?

```
➜  sync-test node test1.js 
module.js:472
    throw err;
    ^

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/josh/projects/sync-test/node_modules/yjs/src/y.js:11:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

```

**Comment by dmonad** [comment]
This is definitely a bug. Thanks for reporting!
